c_compiler_version:            # [osx]
  - 18                         # [osx]
cxx_compiler_version:          # [osx]
  - 18                         # [osx]
llvm_openmp:                   # [osx]
  - 18                         # [osx]
clang_compiler_version:
  - 18
clangxx_compiler_version:
  - 18
